# Generated by Django 5.0.6 on 2024-07-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=20)),
                ('email1', models.EmailField(max_length=20)),
                ('ph', models.IntegerField()),
                ('msg', models.CharField(max_length=255)),
            ],
        ),
    ]
