# Generated by Django 5.0.6 on 2024-07-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdesign', '0002_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='art',
        ),
    ]
